
GET  http://localhost:9001/
Content-Type: application/json


###


POST http://localhost:9001/api/v1/task/add
Content-Type: application/json

{
    "title": "Belajar Algoritma dan Struktur Data",
    "action_time": "1998-07-04",
    "is_Finished": true,
    "objective_list": [{"objective_Name": "menonton video", "is_Finished": false}, {"objective_Name": "membaca buku", "is_Finished": false}]
}


###

GET http://localhost:9001/task/get/7

###

GET http://localhost:9001/task/obj/2
Content-Type: application/json


###

DELETE http://localhost:9001/task/delete/7
Content-Type: application/json
